### ISSUE TITLE
Exit via Ctrl+Z

### ISSUE THREAD

**Issue by zty012** [mtoyoda/sl#80]
1. sl
2. Ctrl Z

**Comment by zty012** [comment]
[![asciicast](https://asciinema.org/a/MYynoF83oMXKg21wB7HSIaV2c.svg)](https://asciinema.org/a/MYynoF83oMXKg21wB7HSIaV2c)

**Comment by matoken** [comment]
> 1. sl
> 2. Ctrl Z
3. kill %1

**Comment by mtoyoda** [comment]
That is intentionally allowed :-)
